### ISSUE TITLE
 [BUG] DAW becomes unresponsible when CMT is automated with LFO

### ISSUE THREAD

**Issue by Witcharrr** [Chowdhury-DSP/ChowMultiTool#41] opened 2024-06-10 08:02 UTC
**Describe the bug**
DAW becomes unresponsible, when ChowMultiTool 1.1.0 is automated with LFO. Tested both in Renoise and Reaper.

**To Reproduce**

**In Renoise:**
1. Add LFO on the effects panel
2. Add ChowMultiTool on the effects panel
3. Choose from presets: "Chow -> Analog EQ -> Excite"
4. In LFO dest. select "VST3: chowdsp: ChowMultiTool" and "Analog EQ Treble Cut Frequency" (actually any Analog EQ parameter will do)
5. Now DAW is unresponsible, and eats 15-20% CPU

**In REAPER**
1. Right-click on left panel -> Insert new track
2. Press FX button
3. Add plugin: All Plugins -> Select ChowMultiTool -> Press "Add" button
4. Choose from presets: "Chow -> Analog EQ -> Excite"
5. Right-click on "Treble boost" dot -> "Analog EQ Treble Boost Frequency" (actually any Analog EQ parameter will do) -> "Show in track controls"
6. A knob with that parameter will be created on current track on the left panel
7. Right-click on this knob, select "Modulate"
8. Tick the LFO checkbox.
9. Play abit with "speed" and "strength" sliders
10. Now DAW is unresponsible, and eats 15-20% CPU

**Expected behavior**
DAW is responsive and automation not breaking anything

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CPU: Intel Core i5-10400F
 - RAM: 64GB DDR4
 - GPU: NVIDIA GeForce RTX 3050
 - Main SSD: Samsung SSD 870 EVO 1TB
 - DAW: Renoise 3.4.4, Reaper 7.16
 - 64 bit

**Comment by jatinchowdhury18** [comment] 2024-06-11 03:32
Thanks for the bug report! I was able to reproduce the same issue in Bitwig. #42 should help the situation for the Analog EQ. Once that PR is merged, it would be great if you could test the next [nightly build](https://chowdsp.com/nightly.html#multitool) to confirm the fix.

I wasn't noticing any issues when automating parameters in the other "tools" but definitely let me know if you have!

**Comment by Witcharrr** [comment] 2024-06-11 07:07
Thanks for quick response! Tried nightly build. Results:
Renoise crashes when ChowMultiTool is added to the fx panel with following error:

```
Vst3Plugs: Instantiating: C:\Program Files\Common Files\VST3\ChowMultiTool.vst3\Contents\x86_64-win\ChowMultiTool.vst3...
Vst3Plugs: Plugin 'chowdsp: ChowMultiTool' crashed while calling one of its plugin factory functions!
Vst3Plugs: Failed to create plugin component instance
Vst3Plugs: Failed to load plugin instance
Vst3Plugs: Releasing: chowdsp: ChowMultiTool...

Audio Plugins: Failed to open plug VST3: ABCDEF019182FAEB43686F774D6C7434

Exception: Failed to initialize the plugin 'VST3: chowdsp: ChowMultiTool'.

Error Message: Failed to initialize the plugin 'VST3: chowdsp: ChowMultiTool'.

CrashLog: Handling Exception! Code : C0000005
CrashLog: 00007FFBFB1D16B0: ??? +00000
CrashLog: 00007FFC983EEF75: CallWindowProcW +00615
CrashLog: 0000000008430988: ??? +00000
CrashLog: 0000000000000001: ??? +00000

Application: Caught an unhandled fatal exception (Thread: GUI)!
Application: Saving a backup...

Error Message: A fatal error or crash occurred (unhandled exception in thread: GUI).
Error Message: A backup of the current document was saved at
Error Message: 'C:\Users\Witcharrr\AppData\Roaming\Renoise\V3.4.4\CrashBackups\Untitled_6_11_2024__10_0_crash.xrns'...
Error Message: This either happened because of a bug in Renoise, or because of a bug in one of its loaded components (plugins). Please contact <bug@renoise.com> and report this problem, so that it can be fixed.
Error Message: Note: It's very important that we know exactly what has happened (what you were doing before this message popped up), or the problem cannot be replicated/analyzed. Please include a description of what you were doing and which components were being used...

CrashLog: Handling Exception! Code : C0000005
CrashLog: 00007FFBFB1D16B0: ??? +00000
CrashLog: 00007FFC983EEF75: CallWindowProcW +00615
CrashLog: 00007FFC983EE69D: DispatchMessageW +004AD
CrashLog: 0000000140710736: l9_ippsLn_32f_A21 +342C46
CrashLog: 00000001407AD808: l9_ippsLn_32f_A21 +3DFD18
CrashLog: 00000001407B15DE: l9_ippsLn_32f_A21 +3E3AEE
CrashLog: 00000001406A570C: l9_ippsLn_32f_A21 +2D7C1C
CrashLog: 0000000140705EBA: l9_ippsLn_32f_A21 +3383CA
CrashLog: 00000001406B3F12: l9_ippsLn_32f_A21 +2E6422
CrashLog: 000000014071AE84: l9_ippsLn_32f_A21 +34D394
CrashLog: 000000014071FD3D: l9_ippsLn_32f_A21 +35224D
CrashLog: 00000001403FD6E3: l9_ippsLn_32f_A21 +2FBF3
CrashLog: 00000001403F8840: l9_ippsLn_32f_A21 +2AD50
CrashLog: 00000001403FDFD6: l9_ippsLn_32f_A21 +304E6
CrashLog: 0000000140DE7E43: l9_ippsLn_32f_A21 +A1A353
CrashLog: 00007FFC968C7344: BaseThreadInitThunk +00014
CrashLog: 00007FFC986E26B1: RtlUserThreadStart +00021
```
In Reaper the plugin just isn't detected now.

**Comment by jatinchowdhury18** [comment] 2024-06-12 23:07
Hmmm, that's a bit strange, I was able to load that build into both Reaper (v6.8.1) and Renoise (v3.4.4, Demo).

One thing that could be useful would be to check the plugin logs (`C:\Users\<Your Username>\AppData\Roaming\ChowdhuryDSP\ChowMultiTool\Logs`).

**Comment by Witcharrr** [comment] 2024-06-13 02:02
Checked the logs folder, but since i've updated ChowMultiTool to the nightly build it doesn't make any logs at all. All logs that in "Logs" folder are from stable version. Tried to uninstall CMT and install again - same thing, here's a video: 

https://github.com/Chowdhury-DSP/ChowMultiTool/assets/14049568/1096af6c-0ea5-4324-b9db-655da51bb492


What about Reaper, it shows any other plugins of yours except of CMT (just to be sure, during re-installation i've installed only vst3 version), though it is in reaper-vstplugins64.ini file as "ChowMultiTool.vst3=00F4CE0C9DBBDA01": 
![2024-06-13 04_56_45-Clipboard](https://github.com/Chowdhury-DSP/ChowMultiTool/assets/14049568/bca64c35-0ae3-4671-a665-9ae4a809e1dc)
UPD: Strangely, i've reinstalled CMT again, but with CLAP version of plugin - reaper sees only CLAP version now, but also crashes when i'm trying to load it.
Since there no crash logs in Reaper, maybe it'll help if i provide some error logs from Windows' Event Viewer for both applications:
**Renoise**
```
Faulting application name: Renoise.exe, version: 3.4.4.0, time stamp: 0x663a057a
Faulting module name: ChowMultiTool.vst3_unloaded, version: 0.0.0.0, time stamp: 0x6667cef0
Exception code: 0xc0000005
Fault offset: 0x00000000000516b0
Faulting process id: 0x870
Faulting application start time: 0x01dabd35cc0dc19f
Faulting application path: C:\Program Files\Renoise 3.4.4\Renoise.exe
Faulting module path: ChowMultiTool.vst3
Report Id: 00110b31-1ebf-4f95-a397-651ade48dbcf
Faulting package full name: 
Faulting package-relative application ID: 
```
**Reaper**
```
Faulting application name: reaper.exe, version: 7.1.6.0, time stamp: 0x664d12ff
Faulting module name: MSVCP140.dll, version: 14.29.30133.0, time stamp: 0x60ff28cc
Exception code: 0xc0000005
Fault offset: 0x0000000000013020
Faulting process id: 0x3290
Faulting application start time: 0x01dabd35e9e78306
Faulting application path: C:\Program Files\REAPER (x64)\reaper.exe
Faulting module path: C:\windows\SYSTEM32\MSVCP140.dll
Report Id: 12fca4e8-abeb-4fd6-842a-66715026acc1
Faulting package full name: 
Faulting package-relative application ID: 
```
UPD2: reinstalled stable build - it loads fine

**Comment by jatinchowdhury18** [comment] 2024-06-13 23:04
![image](https://github.com/Chowdhury-DSP/ChowMultiTool/assets/13724188/bcf2e2f9-a43b-490c-91e4-136ddc5c0c45)
![Screenshot 2024-06-13 155745](https://github.com/Chowdhury-DSP/ChowMultiTool/assets/13724188/ce95934b-ea7b-4189-b8b5-8e5a7034b07f)

Hmm okay... I'm really not sure where to go from here. I'm currently able to load the latest nightly build in both Renoise 3.4.4 and Reaper 7.16, which I believe are the same versions that you're testing with? The only other difference is that I'm currently on Windows 11, but I'm not sure that it's possible for me to down-grade to Windows 10 at the moment. If I'm not able to reproduce the crashing behaviour, then I'm afraid there may not be much that I can do to fix it.

My suggestion would be to:
- Manually delete all instances of the plugin from your machine
- Open your DAW(s) to verify that the plugin is not being scanned
- Close your DAW(s)
- Re-install the nightly build from the website

Hopefully that works, but if it doesn't then I'm not really sure what else to do.

**Comment by Witcharrr** [comment] 2024-06-14 08:55
Strangely, after some uninstall/install iterations now it works somehow 🤷‍♂️ Or maybe reinstallation of latest Visual C++ Redistributable helped, idk. But anyway, i've found another bug now that crashes DAW - both Reaper and Renoise. How to replicate:
1) Select Analog EQ, and "Flat" preset.
2) Automate Treble Boost Frequency Band (or any band will do i think) with LFO
3) Click "Next" arrow to switch both type and preset
4) Now DAW is crashed
Also, sometimes CMT crashes DAW when switching between Analog EQ - Flat preset and Band Splitter - 2-way split/3-way split, if you're clicking fast enough. Sometimes it's almost instant, and sometimes to replicate this you need some more time. Here's a video:

https://github.com/Chowdhury-DSP/ChowMultiTool/assets/14049568/39f26db0-dace-47a3-964e-78238c6485f3

**Comment by jatinchowdhury18** [comment] 2024-06-17 05:49
Oh interesting... yeah, maybe something had gotten corrupted in the previous installation and was repaired in the new installation.

Thanks for testing out the change, and good catch noticing the new bug. Fortunately, I believe that was a simple one to solve (see #43). Again, there will be a new Nightly build available in a few hours if you would like to test it!

**Comment by Witcharrr** [comment] 2024-06-18 12:18
Tested the latest nightly build - seems like CMT working as it should now. Thanks!

**Comment by jatinchowdhury18** [comment] 2024-06-18 17:54
Awesome! Thanks again for reporting :)

**Closed as completed by jatinchowdhury18** 2024-06-18 17:54 UTC
Labels: bug
